apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: {{ .Values.namespace }}
data:
  opensearch.yml: |
    cluster.name: ticket-booking-logs
    network.host: 0.0.0.0
    discovery.type: single-node
    plugins.security.disabled: true
    bootstrap.memory_lock: false
    OPENSEARCH_JAVA_OPTS: {{ .Values.opensearch.javaOpts | quote }}
