sonar.projectKey=hlocuwu_ticket-booking-payment
sonar.organization=hlocuwu
sonar.projectName=ticket-booking-payment
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
