server {
    listen 80;

    # Serve the React static files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Route /api/auth traffic to the Auth service
    location /api/auth/ {
        proxy_pass http://ticket_auth_service:8080/;
        proxy_set_header Host $host;
    }

    # Route /api/events traffic to the Event service
    location /api/events/ {
        proxy_pass http://ticket_event_service:8080/;
        proxy_set_header Host $host;
    }

    # Route /api/queue traffic to the Waiting Room service
    location /api/queue/ {
        proxy_pass http://ticket_waitingroom_service:8080/;
        proxy_set_header Host $host;
    }

    # Route /api/booking traffic to the Booking orchestrator
    location /api/booking/ {
        proxy_pass http://ticket_booking_service:8080/;
        proxy_set_header Host $host;
    }
}