sonar.projectKey=hlocuwuu_ticket-booking
sonar.organization=hlocuwuu
sonar.projectName=ticket-booking

sonar.sources=src
sonar.exclusions=\
  src/**/node_modules/**,\
  src/**/dist/**,\
  src/**/*_test.go,\
  src/**/*.pb.go,\
  src/**/coverage/**

sonar.tests=src
sonar.test.inclusions=\
  src/**/*_test.go,\
  src/**/tests/**/*.test.js,\
  src/**/tests/**/*.py

sonar.go.coverage.reportPaths=coverage-auth.out,coverage-booking.out,coverage-event.out,coverage-inventory.out,coverage-waitingroom.out
sonar.javascript.lcov.reportPaths=src/services/payment/coverage/lcov.info,src/frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=src/services/notification/coverage.xml
