apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hlocuwu/ticket-booking.git
    targetRevision: HEAD
    path: manifest/helm/logging
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: opensearchDashboards.ingress.host
          value: opensearch.flashticket.site
        - name: tls.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
