apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-booking
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hlocuwu/ticket-booking.git
    targetRevision: HEAD
    path: manifest/helm/ticket-booking
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: db.host
          value: "172.27.209.3"
        - name: redis.host
          value: "172.27.208.3"
        - name: externalSecrets.enabled
          value: "true"
        - name: externalSecrets.createClusterStore
          value: "true"
        - name: externalSecrets.gcpProjectId
          value: "ticket-booking-cloud"
        - name: externalSecrets.clusterName
          value: "ticket-booking-cloud-gke"
        - name: tls.enabled
          value: "true"
        - name: tls.acmeEmail
          value: "nhloc08@gmail.com"
        - name: ingress.host
          value: "flashticket.site"
  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-booking
  ignoreDifferences:
    - group: cert-manager.io
      kind: ClusterIssuer
      jsonPointers:
        - /status
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /metadata/annotations/force-sync
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/target/deletionPolicy
        - /spec/target/template/engineVersion
        - /spec/target/template/mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
