apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-booking-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hlocuwu/ticket-booking.git
    targetRevision: staging
    path: manifest/helm/ticket-booking
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-booking-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
