apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ .Values.namespace }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.{{ .Values.namespace }}.svc.cluster.local:9090
        isDefault: true
        editable: true

  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: default
        folder: Ticket Booking
        type: file
        options:
          path: /var/lib/grafana/dashboards
