apiVersion: v1
kind: Service
metadata:
  name: waitingroom
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ticket-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: waitingroom
spec:
  selector:
    {{- include "ticket-booking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: waitingroom
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
