apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ticket-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |
    server {
        listen 80;

        add_header X-Frame-Options           "SAMEORIGIN"                               always;
        add_header X-Content-Type-Options    "nosniff"                                  always;
        add_header X-XSS-Protection          "1; mode=block"                            always;
        add_header Referrer-Policy           "strict-origin-when-cross-origin"          always;
        add_header Permissions-Policy        "geolocation=(), microphone=(), camera=()" always;
        add_header Content-Security-Policy
            "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; font-src 'self' data:;"
            always;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/auth/ {
            proxy_pass http://auth:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/events/ {
            proxy_pass http://event:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/queue/ {
            proxy_pass http://waitingroom:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/booking/ {
            proxy_pass http://booking:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/notification/ {
            proxy_pass http://notification:8086/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/inventory/ {
            proxy_pass http://inventory:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payment/ {
            proxy_pass http://payment:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
