{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProjectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.clusterLocation | quote }}
          clusterName: {{ .Values.externalSecrets.clusterName | quote }}
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ticket-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: ticket-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: ticket-booking-db-password
    - secretKey: jwt-secret
      remoteRef:
        key: ticket-booking-jwt-secret
    - secretKey: smtp-username
      remoteRef:
        key: ticket-booking-smtp-username
    - secretKey: smtp-password
      remoteRef:
        key: ticket-booking-smtp-password
    - secretKey: sender-email
      remoteRef:
        key: ticket-booking-sender-email
    - secretKey: momo-access-key
      remoteRef:
        key: ticket-booking-momo-access-key
    - secretKey: momo-secret-key
      remoteRef:
        key: ticket-booking-momo-secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    type: kubernetes.io/dockerconfigjson
    template:
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"hlocuwu","password":"{{ "{{" }} .token {{ "}}" }}","auth":"{{ "{{" }} list "hlocuwu" .token | join ":" | b64enc {{ "}}" }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: ticket-booking-ghcr-token
{{- end }}
