apiVersion: v1
kind: Secret
metadata:
  name: ticket-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ticket-booking.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password:     {{ .Values.secrets.dbPassword     | default "" | quote }}
  jwt-secret:      {{ .Values.secrets.jwtSecret      | default "" | quote }}
  smtp-username:   {{ .Values.secrets.smtpUsername   | default ""                                 | quote }}
  smtp-password:   {{ .Values.secrets.smtpPassword   | default ""                                 | quote }}
  sender-email:    {{ .Values.secrets.senderEmail     | default ""                                 | quote }}
  momo-access-key: {{ .Values.secrets.momoAccessKey  | default ""                                 | quote }}
  momo-secret-key: {{ .Values.secrets.momoSecretKey  | default ""                                 | quote }}
