sonar.projectKey=hlocuwu_ticket-booking-event
sonar.organization=hlocuwu
sonar.projectName=ticket-booking-event
sonar.sources=.
sonar.exclusions=**/*_test.go,**/*.pb.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
