sonar.projectKey=hlocuwu_ticket-booking-notification
sonar.organization=hlocuwu
sonar.projectName=ticket-booking-notification
sonar.sources=.
sonar.exclusions=tests/**
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
