namespace: ticket-booking-staging

image:
  tag: latest

app:
  publicUrl: "https://staging.flashticket.site"

db:
  name: ticket_db_staging

ingress:
  className: nginx
  host: staging.flashticket.site  

replicas:
  auth: 1
  booking: 1
  event: 1
  inventory: 1
  notification: 1
  payment: 1
  waitingroom: 1
  frontend: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

tls:
  enabled: true
  acmeEmail: ""
  createClusterIssuer: false

externalSecrets:
  enabled: true
  gcpProjectId: ""       
  clusterLocation: "asia-southeast1-a"
  clusterName: ""        
