image:
  tag: latest

db:
  name: ticket_db

app:
  publicUrl: "https://flashticket.site"

ingress:
  className: nginx
  host: flashticket.site

replicas:
  auth: 2
  booking: 2
  event: 2
  inventory: 2
  notification: 1
  payment: 2
  waitingroom: 2
  frontend: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

tls:
  enabled: true
  acmeEmail: ""

externalSecrets:
  enabled: true
  gcpProjectId: ""        
  clusterLocation: "asia-southeast1-a"
  clusterName: ""
