namespace: ticket-booking

image:
  registry: ghcr.io
  owner: hlocuwu
  tag: v0.2.1
  pullPolicy: IfNotPresent
  pullSecret: ghcr-pull-secret

db:
  host: ""
  port: "5432"
  user: ticket_admin
  name: ticket_db

redis:
  host: ""
  port: "6379"

app:
  publicUrl: "https://flashticket.site"

payment:
  publicUrl: "https://flashticket.site"
  momo:
    partnerCode: "MOMO"
    endpoint: "https://test-payment.momo.vn/v2/gateway/api/create"

smtp:
  server: smtp.gmail.com
  port: "587"

ingress:
  className: nginx
  host: flashticket.site

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

queue:
  maxConcurrent: 50 

replicas:
  auth: 1
  booking: 1
  event: 1
  inventory: 1
  notification: 1
  payment: 1
  waitingroom: 1
  frontend: 1

hpa:
  auth:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  booking:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 60
    targetMemory: 80
  event:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 60
    targetMemory: 80
  inventory:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 60
    targetMemory: 80
  waitingroom:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  payment:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  notification:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPU: 70
    targetMemory: 80
  frontend:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80

secrets:
  dbPassword: ""
  jwtSecret: ""
  smtpUsername: ""
  smtpPassword: ""
  senderEmail: ""
  momoAccessKey: ""
  momoSecretKey: ""

tls:
  enabled: false
  acmeEmail: ""
  createClusterIssuer: true

externalSecrets:
  enabled: false
  createClusterStore: false
  gcpProjectId: ""
  clusterLocation: "asia-southeast1-a"
  clusterName: ""
